from enum import Enum


class ExcludedPermCondition(Enum):
    not_crooked_jaw = "-crooked_jaw"
    not_lost_a_leg = "-lost_leg"
    not_born_without_a_leg = "-born_without_leg"
    not_weak_leg = "-weak_leg"
    not_twisted_leg = "-twisted_leg"
    not_lost_their_tail = "-lost_tail"
    not_born_without_a_tail = "-born_without_tail"
    not_paralyzed = "-paralyzed"
    not_raspy_lungs = "-raspy_lungs"
    not_wasting_disease = "-wasting_disease"
    not_blind = "-blind"
    not_one_bad_eye = "-one_bad_eye"
    not_failing_eyesight = "-failing_eyesight"
    not_partial_hearing_loss = "-partial_hearing_loss"
    not_deaf = "-deaf"
    not_constant_joint_pain = "-constant_joint_pain"
    not_seizure_prone = "-seizure_prone"
    not_allergies = "-allergies"
    not_constantly_dizzy = "-constantly_dizzy"
    not_recurring_shock = "-recurring_shock"
    not_lasting_grief = "-lasting_grief"
    not_persistent_headaches = "-persistent_headaches"
