from enum import Enum


class Herb(Enum):
    elder_leaves = "elder_leaves"
    cobwebs = "cobwebs"
    daisy = "daisy"
    horsetail = "horsetail"
    juniper = "juniper"
    lungwort = "lungwort"
    mallow = "mallow"
    marigold = "marigold"
    moss = "moss"
    oak_leaves = "oak_leaves"
    ragwort = "ragwort"
    raspberry = "raspberry"
    tansy = "tansy"
    thyme = "thyme"
    wild_garlic = "wild_garlic"
    dandelion = "dandelion"
    mullein = "mullein"
    rosemary = "rosemary"
    burdock = "burdock"
    blackberry = "blackberry"
    betony = "betony"
    goldenrod = "goldenrod"
    poppy = "poppy"
    plantain = "plantain"
    catmint = "catmint"
