from enum import Enum


class Illness(Enum):
    seizure = "seizure"
    diarrhea = "diarrhea"
    fleas = "fleas"
    greencough = "greencough"
    kittencough = "kittencough"
    an_infected_wound = "infection"
    carrionplace_disease = "carrionplace_disease"
    redcough = "redcough"
    running_nose = "running_nose"
    whitecough = "whitecough"
    yellowcough = "yellowcough"
    a_festering_wound = "festering_wound"
    heat_stroke = "heat_stroke"
    heat_exhaustion = "heat_exhaustion"
    stomachache = "stomachache"
    constant_nightmares = "constant_nightmares"
    grief_stricken = "grief_stricken"
    malnourished = "malnourished"
    starving = "starving"
    sore_throat = "sore_throat"
    tick_fever = "tick_fever"
    breathless_fit = "breathless_fit"
    diarrhea_dehydrated = "diarrhea_dehydrated"
