from enum import Enum


class PermCondition(Enum):
    crooked_jaw = "crooked_jaw"
    lost_a_leg = "lost_leg"
    born_without_a_leg = "born_without_leg"
    weak_leg = "weak_leg"
    twisted_leg = "twisted_leg"
    lost_their_tail = "lost_tail"
    born_without_a_tail = "born_without_tail"
    paralyzed = "paralyzed"
    raspy_lungs = "raspy_lungs"
    wasting_disease = "wasting_disease"
    blind = "blind"
    one_bad_eye = "one_bad_eye"
    failing_eyesight = "failing_eyesight"
    partial_hearing_loss = "partial_hearing_loss"
    deaf = "deaf"
    constant_joint_pain = "constant_joint_pain"
    seizure_prone = "seizure_prone"
    allergies = "allergies"
    constantly_dizzy = "constantly_dizzy"
    recurring_shock = "recurring_shock"
    lasting_grief = "lasting_grief"
    persistent_headaches = "persistent_headaches"
