from enum import Enum


class Trait(Enum):
    troublesome = "troublesome"
    lonesome = "lonesome"
    fierce = "fierce"
    bloodthirsty = "bloodthirsty"
    cold = "cold"
    childish = "childish"
    playful = "playful"
    charismatic = "charismatic"
    bold = "bold"
    daring = "daring"
    nervous = "nervous"
    righteous = "righteous"
    insecure = "insecure"
    strict = "strict"
    compassionate = "compassionate"
    thoughtful = "thoughtful"
    ambitious = "ambitious"
    confident = "confident"
    adventurous = "adventurous"
    calm = "calm"
    careful = "careful"
    faithful = "faithful"
    loving = "loving"
    loyal = "loyal"
    responsible = "responsible"
    shameless = "shameless"
    sneaky = "sneaky"
    strange = "strange"
    vengeful = "vengeful"
    wise = "wise"
    arrogant = "arrogant"
    competitive = "competitive"
    grumpy = "grumpy"
    cunning = "cunning"
    oblivious = "oblivious"
    gloomy = "gloomy"
    sincere = "sincere"
    flamboyant = "flamboyant"
    rebellious = "rebellious"
