name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: "Automatically label PR based on changed files"
      uses: actions/labeler@v6
      with:
        sync-labels: true
